CREATE DATABASE DB_HENRIQUE_GOMES;
CREATE TABLE ESPORTES (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (100),
QUANTIDADE_DE_PARTICIPANTES INT,
DETALHES VARCHAR (100),
DIFICULDADE VARCHAR (100));
INSERT INTO ESPORTES (NOME, QUANTIDADE_DE_PARTICIPANTES, DETALHES, DIFICULDADE)
VALUES ('Basquete', 10, 'O melhor esporte para assistir', 'dificuldade média');
INSERT INTO ESPORTES (NOME, QUANTIDADE_DE_PARTICIPANTES, DETALHES, DIFICULDADE)
VALUES ('Futebol', 22, 'O maior esporte do mundo', 'dificuldade baixa');
INSERT INTO ESPORTES (NOME, QUANTIDADE_DE_PARTICIPANTES, DETALHES, DIFICULDADE)
VALUES ('Vôlei', 12, 'O esporte mais divertido', 'dificuldade alta');
INSERT INTO ESPORTES (NOME, QUANTIDADE_DE_PARTICIPANTES, DETALHES, DIFICULDADE)
VALUES ('Handebol', 10, 'O esporte menos valorizado', 'dificuldade alta');
INSERT INTO ESPORTES (NOME, QUANTIDADE_DE_PARTICIPANTES, DETALHES, DIFICULDADE)
VALUES ('Natação', 8, 'O esporte mais cansativo', 'dificuldade alta');